import type { Product } from '@workspace/types';

export const products: Product[] = [
  {
    id: 'pixel',
    name: 'Pixel',
    slug: 'pixel',
    tagline: 'ROS2 SLAM education kit',
    description: '',
    features: [
      'Intel RealSense 3D depth camera',
      '2D LiDAR with 30m range',
      '4 proximity sensors + IMU',
      'ROS2 navigation learning workflows',
      'Wi-Fi 2.4/5 GHz connectivity',
      'Emergency stop kill switch',
    ],
    specifications: {
      Dimensions: '600 x 400 x 300 mm',
      'Payload Capacity': '300 kg',
      Speed: '1.5 m/s',
      Battery: '24V Li-Ion',
      'Run Time': '8 hours',
      Navigation: 'LiDAR + Visual SLAM',
    },
    image: '/Product/pixel/pixel.png',
    images: [
      '/Product/pixel/pixel.png',
      '/Product/pixel/pixel1.png',
      '/Product/pixel/9.png',
      '/Product/pixel/8.png',
      '/Product/pixel/pixel front.png',
      '/Product/pixel/12.png',
      '/Product/pixel/14.png',
      '/Product/pixel/21.png',
      '/Product/pixel/Pixel diagram.png',
    ],
    category: 'amr',
    industries: ['education'],
  },
  {
    id: 'orbit',
    name: 'Orbit',
    slug: 'orbit',
    tagline: 'Multi-robot coordination education platform',
    description: '',
    features: [
      'Multi-robot fleet coordination',
      'Advanced path planning',
      'Sensor fusion learning',
      'Fleet management workflows',
      'Scalable for research',
    ],
    specifications: {
      Dimensions: '1200 x 800 x 500 mm',
      'Payload Capacity': '1000 kg',
      Speed: '1.2 m/s',
      Battery: '48V Li-Ion',
      'Run Time': '12 hours',
      Navigation: 'LiDAR + IMU + Odometry',
    },
    image: '/Product/orbit/11.png',
    images: [
      '/Product/orbit/11.png',
      '/Product/orbit/9.png',
    ],
    category: 'amr',
    industries: ['education'],
  },
  {
    id: 'cyborg',
    name: 'Cyborg',
    slug: 'cyborg',
    tagline: 'Industrial AMR',
    description: '',
    features: [
      'Modular design',
      'Open integration API',
      'Configurable payload deck',
      'Swappable sensor modules',
      'Remote fleet management',
      'Multiple payload variants',
    ],
    specifications: {
      Navigation: 'LiDAR + Camera + IMU',
      Battery: '24V–48V Li-Ion',
      'Run Time': '8–16 hours',
      Speed: '0.8–1.2 m/s',
    },
    image: '/Product/cyborg/Cyborg.png',
    images: [
      '/Product/cyborg/Cyborg.png',
      '/Product/cyborg/specifications/cyborg150.jpg',
      '/Product/cyborg/specifications/cyborg250.jpg',
      '/Product/cyborg/specifications/cyborg500.jpg',
    ],
    category: 'amr',
    industries: ['pharma', 'automotive', 'manufacturing', 'warehouses-logistics'],
    variants: [
      {
        id: 'cyborg-150',
        name: 'Cyborg 150',
        slug: 'cyborg-150',
        payload: '150 kg',
        specifications: {
          Dimensions: '700 x 450 x 200 mm',
          'Payload Capacity': '150 kg',
          Speed: '1.8 m/s',
          Battery: 'LiFePO4 24V 40Ah',
          'Run Time': '5-6 hours',
        },
      },
      {
        id: 'cyborg-250',
        name: 'Cyborg 250',
        slug: 'cyborg-250',
        payload: '250 kg',
        specifications: {
          Dimensions: '900 x 600 x 400 mm',
          'Payload Capacity': '250 kg',
          Speed: '1.0 m/s',
          Battery: '36V Li-Ion',
          'Run Time': '10 hours',
        },
      },
      {
        id: 'cyborg-500',
        name: 'Cyborg 500',
        slug: 'cyborg-500',
        payload: '500 kg',
        specifications: {
          Dimensions: '1400 x 900 x 550 mm',
          'Payload Capacity': '500 kg',
          Speed: '1.0 m/s',
          Battery: '48V Li-Ion',
          'Run Time': '14 hours',
        },
      },
      {
        id: 'cyborg-1000',
        name: 'Cyborg 1000',
        slug: 'cyborg-1000',
        payload: '1000 kg',
        specifications: {
          Dimensions: '1800 x 1100 x 650 mm',
          'Payload Capacity': '1000 kg',
          Speed: '0.8 m/s',
          Battery: '48V Li-Ion',
          'Run Time': '16 hours',
        },
      },
    ],
  },
];
