import type { Product } from '@workspace/types';

export const products: Product[] = [
  {
    id: 'pixel',
    name: 'Pixel',
    slug: 'pixel',
    tagline: 'ROS2 SLAM education kit',
    description:
      'Pixel is a compact learning platform for teams, labs, and institutes that want to understand ROS2, SLAM, navigation, sensors, mapping, and autonomous robot behavior through a real mobile robot kit.',
    features: [
      'Intel RealSense 3D depth camera',
      '2D LiDAR with 30m range',
      '4 proximity sensors + IMU',
      'ROS2 navigation learning workflows',
      'Wi-Fi 2.4/5 GHz connectivity',
      'Emergency stop kill switch',
    ],
    specifications: {
      Dimensions: '600 x 400 x 300 mm',
      'Payload Capacity': '100 kg',
      Speed: '1.5 m/s',
      Battery: '24V Li-Ion',
      'Run Time': '8 hours',
      Navigation: 'LiDAR + Visual SLAM',
    },
    image: '/Product/pixel/pixel.png',
    images: [
      '/Product/pixel/pixel.png',
      '/Product/pixel/pixel1.png',
      '/Product/pixel/9.png',
      '/Product/pixel/8.png',
      '/Product/pixel/pixel front.png',
      '/Product/pixel/12.png',
      '/Product/pixel/14.png',
      '/Product/pixel/21.png',
      '/Product/pixel/Pixel diagram.png',
    ],
    category: 'amr',
    industries: ['warehouses-logistics', 'manufacturing', 'fmcg'],
  },
  {
    id: 'orbit',
    name: 'Orbit',
    slug: 'orbit',
    tagline: 'Larger-scale ROS2 navigation platform',
    description:
      'Orbit takes the Pixel learning path to a larger physical scale. It helps advanced teams study navigation, mapping, sensor fusion, and payload movement on a platform that can carry weight and simulate real industrial routes.',
    features: [
      'Larger chassis for applied navigation training',
      'Payload-carrying research workflows',
      'Multi-sensor fusion experiments',
      'Route testing for industrial layouts',
      'Fleet behavior learning path',
      'LED status indicators',
    ],
    specifications: {
      Dimensions: '1200 x 800 x 500 mm',
      'Payload Capacity': '500 kg',
      Speed: '1.2 m/s',
      Battery: '48V Li-Ion',
      'Run Time': '12 hours',
      Navigation: 'LiDAR + IMU + Odometry',
    },
    image: '/Product/orbit/orbit.png',
    images: [
      '/Product/orbit/orbit.png',
      '/Product/orbit/orbit1.png',
      '/Product/orbit/11.png',
      '/Product/orbit/9.png',
    ],
    category: 'amr',
    industries: ['automotive', 'manufacturing', 'warehouses-logistics'],
  },
  {
    id: 'cyborg',
    name: 'Cyborg',
    slug: 'cyborg',
    tagline: 'Industrial AMR for factories and warehouses',
    description:
      'Cyborg is Momentum Robotics' industrial load-carrying AMR for factories, warehouses, line-side movement, and internal logistics. It is the product platform for real operations, with variants planned around payload and deployment needs.',
    features: [
      'Modular payload architecture',
      'Integration-ready API layer',
      'Configurable payload deck',
      'Swappable sensor modules',
      'Remote fleet management',
      'Multiple payload variants',
    ],
    specifications: {
      Navigation: 'LiDAR + Camera + IMU',
      Battery: '24V-48V Li-Ion',
      'Run Time': '8-16 hours',
      Speed: '0.8-1.2 m/s',
    },
    image: '/Product/cyborg/Cyborg.png',
    images: [
      '/Product/cyborg/Cyborg.png',
    ],
    category: 'amr',
    industries: ['pharma', 'hotels-resorts', 'education', 'automotive', 'manufacturing', 'airports'],
    variants: [
      {
        id: 'cyborg-150',
        name: 'Cyborg 150',
        slug: 'cyborg-150',
        payload: '150 kg',
        image: '/Product/cyborg/Cyborg.png',
        specificationImage: '/Product/cyborg/specifications/cyborg150.jpg',
        specifications: {
          Dimensions: '700 x 450 x 200 mm',
          'Payload Capacity': '150 kg',
          Speed: '1.8 m/s',
          Battery: 'LiFePO4 24V 40Ah',
          'Run Time': '5-6 hours',
        },
      },
      {
        id: 'cyborg-250',
        name: 'Cyborg 250',
        slug: 'cyborg-250',
        payload: '250 kg',
        image: '/Product/cyborg/Cyborg.png',
        specificationImage: '/Product/cyborg/specifications/cyborg250.jpg',
        specifications: {
          Dimensions: '900 x 600 x 400 mm',
          'Payload Capacity': '250 kg',
          Speed: '1.0 m/s',
          Battery: '36V Li-Ion',
          'Run Time': '10 hours',
        },
      },
      {
        id: 'cyborg-500',
        name: 'Cyborg 500',
        slug: 'cyborg-500',
        payload: '500 kg',
        image: '/Product/cyborg/Cyborg.png',
        specificationImage: '/Product/cyborg/specifications/cyborg500.jpg',
        specifications: {
          Dimensions: '1400 x 900 x 550 mm',
          'Payload Capacity': '500 kg',
          Speed: '1.0 m/s',
          Battery: '48V Li-Ion',
          'Run Time': '14 hours',
        },
      },
      {
        id: 'cyborg-1000',
        name: 'Cyborg 1000',
        slug: 'cyborg-1000',
        payload: '1000 kg',
        image: '/Product/cyborg/Cyborg.png',
        specifications: {
          Dimensions: '1800 x 1100 x 650 mm',
          'Payload Capacity': '1000 kg',
          Speed: '0.8 m/s',
          Battery: '48V Li-Ion',
          'Run Time': '16 hours',
        },
      },
    ],
  },
];
