import type { Industry } from '@workspace/types';

export const industries: Industry[] = [
  {
    id: 'automotive',
    name: 'Automotive',
    slug: 'automotive',
    tagline: '',
    description: '',
    icon: 'Car',
    solutions: [],
    image: '/industries/6904ac0e507b4eaf85d5be53_Application-4.png',
  },
  {
    id: 'manufacturing',
    name: 'Manufacturing',
    slug: 'manufacturing',
    tagline: '',
    description: '',
    icon: 'Factory',
    solutions: ['warehouse-automation'],
    image: '/Assets/Square_metalcut.avif',
  },
  {
    id: 'warehouses-logistics',
    name: 'Warehouses & Logistics',
    slug: 'warehouses-logistics',
    tagline: '',
    description: '',
    icon: 'Warehouse',
    solutions: ['warehouse-automation', 'inventory-management'],
    image: '/industries/arno-senoner-bCgsKqFzUcg-unsplash.jpg',
  },
  {
    id: 'pharma',
    name: 'Pharma',
    slug: 'pharma',
    tagline: '',
    description: '',
    icon: 'Pill',
    solutions: [],
    image: '/Assets/draw.avif',
  },
  {
    id: 'fmcg',
    name: 'FMCG',
    slug: 'fmcg',
    tagline: '',
    description: '',
    icon: 'Package',
    solutions: ['warehouse-automation'],
    image: '/industries/refinary.jpg',
  },
  {
    id: 'education',
    name: 'Education',
    slug: 'education',
    tagline: '',
    description: '',
    icon: 'GraduationCap',
    solutions: ['education-automation'],
    image: '/Assets/drawing.avif',
  },
  {
    id: 'hotels-resorts',
    name: 'Hotels & Resorts',
    slug: 'hotels-resorts',
    tagline: '',
    description: '',
    icon: 'Hotel',
    solutions: [],
    image: '/Assets/hi hand.avif',
  },
  {
    id: 'airports',
    name: 'Airports',
    slug: 'airports',
    tagline: '',
    description: '',
    icon: 'Plane',
    solutions: [],
    image: '/Assets/343x480.png',
  },
];
