import type { Industry } from '@workspace/types';

export const industries: Industry[] = [
  {
    id: 'automotive',
    name: 'Automotive Manufacturing',
    slug: 'automotive',
    tagline: 'TODO: Add automotive tagline',
    description: 'TODO: Add automotive description - focus on JIT delivery, line starvation, OEE improvements',
    icon: 'Car',
    solutions: ['line-side-delivery', 'fleet-management'],
    image: '/industries/6904ac0e507b4eaf85d5be53_Application-4.png',
  },
  {
    id: 'pharma',
    name: 'Pharma & Life Sciences',
    slug: 'pharma',
    tagline: 'TODO: Add pharma tagline',
    description: 'TODO: Add pharma description - focus on compliance, cleanroom, traceability',
    icon: 'Pill',
    solutions: ['fleet-management', 'custom-integration'],
    image: '/Assets/draw.avif',
  },
  {
    id: 'warehouses-logistics',
    name: 'Warehouses & 3PL',
    slug: 'warehouses-logistics',
    tagline: 'TODO: Add warehouse tagline',
    description: 'TODO: Add warehouse description - focus on peak season scaling, WMS integration',
    icon: 'Warehouse',
    solutions: ['warehouse-automation', 'fleet-management'],
    image: '/industries/arno-senoner-bCgsKqFzUcg-unsplash.jpg',
  },
  {
    id: 'fmcg',
    name: 'Food & Beverage / FMCG',
    slug: 'fmcg',
    tagline: 'TODO: Add FMCG tagline',
    description: 'TODO: Add FMCG description - focus on consistent handling, product damage reduction',
    icon: 'Package',
    solutions: ['warehouse-automation', 'fleet-management'],
    image: '/industries/refinary.jpg',
  },
  {
    id: 'electronics',
    name: 'Electronics Manufacturing',
    slug: 'electronics',
    tagline: 'TODO: Add electronics tagline',
    description: 'TODO: Add electronics description - focus on precision, ESD concerns, throughput',
    icon: 'Zap',
    solutions: ['line-side-delivery', 'fleet-management'],
    image: '/Assets/Square_metalcut.avif',
  },
  {
    id: 'education',
    name: 'Education & Research',
    slug: 'education',
    tagline: 'TODO: Add education tagline',
    description: 'TODO: Add education description - focus on ROS 2 learning, industry-grade platform, employment pathway',
    icon: 'GraduationCap',
    solutions: ['custom-integration'],
    image: '/Assets/drawing.avif',
  },
];
